### ISSUE TITLE
existsIn with condition

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [pantor/inja#100] opened 2019-03-31 16:14 UTC
I used to be able to test for the existence of a key then evaluate the value with one if statement, like this:
` ## if existsIn(column, "primary_key") and column/primary_key`
However, that no longer seems to work now and I have to separate the two conditions, like this:
```
## if existsIn(column, "primary_key")
## if column/primary_key
```
Is that expected behavior, or am I doing something wrong?

**Comment by Kvaz1r** [comment] 2019-03-31 19:11
It would be better to have code for reproducing the behaviour. 
I don't see any test for it, but code below print TRUE for me. 

```
#include "inja.hpp"

// Just for convenience
using namespace inja;
using json = nlohmann::json;

int main()
{
    json data;
    data["name"] = "Peter";
    data["city"] = "New York";
    data["names"] = {"Jeff", "Seb", "Peter", "Tom"};
    data["temperature"] = 25.6789;
    data["brother"]["name"] = "Chris";
    data["brother"]["daughters"] = {"Maria", "Helen"};
    data["property"] = "name";
    data["age"] = 29;
    data["is_happy"] = true;
    data["is_sad"] = false;
    data["vars"] = {2, 3, 4, 0, -1, -2, -3};

    render_to(std::cout,
    "{% if upper(\"Peter\") == \"PETER\" and existsIn(brother, \"name\") %}TRUE\n{% endif %}", data);

}
```

**Comment by gi9obru0etuPlc6wozls** [comment] 2019-03-31 19:31
Hi, thank you for the response. Here is code that demonstrates the issue: 
```
#include </usr/local/include/inja//inja.hpp>

// Just for convenience
using namespace inja;
using json = nlohmann::json;

int main()
{
    json data;
    data["is_happy"] = true;

    render_to(std::cout,
    "Happiness 1: {% if exists(\"is_happy\") %}TRUE{% endif %}\n\n", data);

    render_to(std::cout,
    "Happiness 2: {% if exists(\"is_happy\") and is_happy %}TRUE{% else %}FALSE{% endif %}\n\n", data);

    render_to(std::cout,
    "Grumpiness 1: {% if exists(\"is_grumpy\") %}TRUE{% else %}FALSE{% endif %}\n\n", data);

    // Fails because second condition is evaluating even though first condidtion is false
    render_to(std::cout,
    "Grumpiness 2: {% if exists(\"is_grumpy\") and is_grumpy %}TRUE{% else %}FALSE{% endif %}\n\n", data);

}
```

The resulting output is: 
```
Happiness 1: TRUE

Happiness 2: TRUE

Grumpiness 1: FALSE

terminate called after throwing an instance of 'std::runtime_error'
  what():  [inja.exception.render_error] variable 'is_grumpy' not found
Aborted (core dumped)
```
The both conditions are evaluated even though the first condition failed and therefore it throws an exception.

**Comment by Kvaz1r** [comment] 2019-03-31 22:40
The reason for error not in the 'and' operation. 
If you try to evaluate such code it also throw an exception. 

```
render_to(std::cout,
    "Grumpiness 1: {% if is_grumpy %}TRUE{% else %}FALSE{% endif %}\n\n", data);
```

**Comment by gi9obru0etuPlc6wozls** [comment] 2019-03-31 23:15
Yes, but the second operation should not be evaluated if the first is false. Since is_grumpy does not exist, this part of the expression is false.

**Comment by pantor** [comment] 2020-06-29 21:16
I'll close this issue in favor of #147. Thanks for reporting!

**Comment by sdlime** [comment] 2021-01-10 19:38
Still seeing this issue in master and 3.1 using single include. An if statement like:
```
{% exists("keywords") and length(keywords) > 0 %}
  ...
{% endif %}
```
Results in _[inja.exception.render_error] (at 15:37) variable 'keywords' not found_. If I nest if statements things work but the single statement is more concise.

--Steve

**Comment by mbessler** [comment] 2021-01-11 17:42
Just upgraded to 3.1 from 2.1, and seeing the same issue as @sdlime

**Comment by pantor** [comment] 2021-05-17 18:12
This should be fixed now on master. Please use to #195 for any remaining issues on short circuit evaluation.

**Closed by pantor** 2021-05-17 18:12 UTC
Labels: enhancement
